import { contextBridge, ipcRenderer } from "electron";
import type { GamePrototypeWizardInput, ManualCommandRequest, ModelProfileInput, ModelProviderType, RuntimeSettings } from "./main/types.js";

contextBridge.exposeInMainWorld("revoltRuntime", {
  getInitialState: () => ipcRenderer.invoke("runtime:getInitialState"),
  checkUnrealBridge: () => ipcRenderer.invoke("runtime:checkUnrealBridge"),
  testDefaultUnrealConnection: () => ipcRenderer.invoke("runtime:testDefaultUnrealConnection"),
  getMcpStatus: () => ipcRenderer.invoke("runtime:getMcpStatus"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  updateSettings: (settings: RuntimeSettings) => ipcRenderer.invoke("settings:update", settings),
  listHistory: () => ipcRenderer.invoke("history:list"),
  clearHistory: () => ipcRenderer.invoke("history:clear"),
  exportHistory: () => ipcRenderer.invoke("history:export"),
  listApprovals: () => ipcRenderer.invoke("approvals:list"),
  checkPlayableLevel: () => ipcRenderer.invoke("playable:checkLevel"),
  dryRunPlayableFixes: (fixIds: string[]) => ipcRenderer.invoke("playable:dryRunFixes", fixIds),
  createPrototypeDryRunPlan: (input: GamePrototypeWizardInput) => ipcRenderer.invoke("prototype:createDryRunPlan", input),
  getLatestPrototypePlan: () => ipcRenderer.invoke("prototype:getLatestPlan"),
  sendPrototypePlanToGuidedRecipe: (planId: string) => ipcRenderer.invoke("prototype:sendToGuidedRecipe", planId),
  listRecipes: () => ipcRenderer.invoke("recipes:list"),
  previewRecipe: (recipeId: string, values: Record<string, unknown>) => ipcRenderer.invoke("recipes:preview", recipeId, values),
  runRecipeDryRun: (recipeId: string, values: Record<string, unknown>) => ipcRenderer.invoke("recipes:runDryRun", recipeId, values),
  applyApprovedRecipe: (recipeId: string, values: Record<string, unknown>) => ipcRenderer.invoke("recipes:applyApproved", recipeId, values),
  listRecipeRuns: () => ipcRenderer.invoke("recipes:runs"),
  runManualCommand: (request: ManualCommandRequest) => ipcRenderer.invoke("manual:runCommand", request),
  listModelProfiles: () => ipcRenderer.invoke("models:list"),
  saveModelProfile: (input: ModelProfileInput) => ipcRenderer.invoke("models:save", input),
  detectModelProvider: (providerType: ModelProviderType, baseUrl: string) => ipcRenderer.invoke("models:detect", providerType, baseUrl),
  deleteModelProfile: (id: string) => ipcRenderer.invoke("models:delete", id),
  duplicateModelProfile: (id: string) => ipcRenderer.invoke("models:duplicate", id),
  setModelProfileEnabled: (id: string, enabled: boolean) => ipcRenderer.invoke("models:setEnabled", id, enabled),
  setActiveModelProfile: (id: string) => ipcRenderer.invoke("models:setActive", id),
  testModelProfile: (id: string) => ipcRenderer.invoke("models:test", id),
  summarizeProjectWithActiveModel: () => ipcRenderer.invoke("models:summarizeProject"),
  chooseIndexRoot: () => ipcRenderer.invoke("index:chooseRoot"),
  getIndexStats: () => ipcRenderer.invoke("index:stats"),
  startIndexing: (projectRoot: string) => ipcRenderer.invoke("index:start", projectRoot),
  stopIndexing: () => ipcRenderer.invoke("index:stop"),
  clearLocalIndex: () => ipcRenderer.invoke("index:clear")
});
